Bump maven-model from 3.9.2 to 3.9.3 (#3756)
Bumps [maven-model](https://github.com/apache/maven) from 3.9.2 to
3.9.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/apache/maven/releases">maven-model's
releases</a>.</em></p>
<blockquote>
<h2>3.9.3</h2>
<h2><a
href="https://maven.apache.org/docs/3.9.3/release-notes.html">Release
Notes - Maven - Version 3.9.3</a></h2>
<h2>Bug</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7786">MNG-7786</a>] -
Maven Plugin Validation message is misleading</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7795">MNG-7795</a>] -
IllegalArgumentException: 'other' has different root during plugin
validation</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7796">MNG-7796</a>] -
Top directory cannot be computed</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7799">MNG-7799</a>] -
Plugin validation falsely reports there are issues (but shows none)</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7811">MNG-7811</a>] -
Plugins verification - reports are inconsistent</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7818">MNG-7818</a>] -
[REGRESSION] maven improperly excludes hamcrest-core from junit</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7819">MNG-7819</a>] -
Create IT that exercise file locking with snapshots</li>
</ul>
<h2>Improvement</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7698">MNG-7698</a>] -
Allow comments in .mvn/maven.config</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7785">MNG-7785</a>] -
Clean usage of SessionData</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7787">MNG-7787</a>] -
Introduce new options for plugin validation</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7788">MNG-7788</a>] -
Plugin Validation Report should be printed before build summary</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7789">MNG-7789</a>] -
Plugin Dependency Validations use wrong data set</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7806">MNG-7806</a>] -
Plugins verification - remove used in module(s) report</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7823">MNG-7823</a>] -
Make plugin validation level parsing more consistent</li>
</ul>
<h2>Task</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-5987">MNG-5987</a>] -
Document the algorithm calculating the order of plugin executions inside
a phase.</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7743">MNG-7743</a>] -
Make the build work on JDK 20</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7790">MNG-7790</a>] -
Update lifecycle plugins</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7791">MNG-7791</a>] -
Split validation issues into &quot;user actionable&quot; and
&quot;plugin dev actionable&quot;</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7797">MNG-7797</a>] -
Return BRIEF mode, simply map it onto SUMMARY</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7807">MNG-7807</a>] -
Update Super POM plugins</li>
</ul>
<h2>Dependency upgrade</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7800">MNG-7800</a>] -
Upgrade to Maven Resolver 1.9.13</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MNG-7816">MNG-7816</a>] -
Bump maven parent from 39 to 40</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/apache/maven/commit/21122926829f1ead511c958d89bd2f672198ae9f"><code>2112292</code></a>
[maven-release-plugin] prepare release maven-3.9.3</li>
<li><a
href="https://github.com/apache/maven/commit/958112991dc0f0d491881b939ace71f6432e9cf4"><code>9581129</code></a>
[MNG-7823] Improve plugin validation level parsing (<a
href="https://redirect.github.com/apache/maven/issues/1182">#1182</a>)</li>
<li><a
href="https://github.com/apache/maven/commit/b050257c05fa6978019d59adfddd0e32a35d1c20"><code>b050257</code></a>
[MNG-7818] Removed exclusion of hamcrest from JUnit 4 (<a
href="https://redirect.github.com/apache/maven/issues/1178">#1178</a>)</li>
<li><a
href="https://github.com/apache/maven/commit/917e9561cfcf72c16b60e54463d78013a40fb88d"><code>917e956</code></a>
[MNG-7800] Update to resolver 1.9.13 (<a
href="https://redirect.github.com/apache/maven/issues/1180">#1180</a>)</li>
<li><a
href="https://github.com/apache/maven/commit/ec5e1ce59988c087d958eb3276f7299cef756e61"><code>ec5e1ce</code></a>
update logging documentation</li>
<li><a
href="https://github.com/apache/maven/commit/bd71dd72a916600f9493b635d4fd002cc5c6b59e"><code>bd71dd7</code></a>
[MNG-7800] Update resolver to 1.9.12 (<a
href="https://redirect.github.com/apache/maven/issues/1176">#1176</a>)</li>
<li><a
href="https://github.com/apache/maven/commit/98016979eb956b9ead2dd913a97629fc9f283c12"><code>9801697</code></a>
[MNG-7816] Update parent to 40, align maven requirements with those from
plug...</li>
<li><a
href="https://github.com/apache/maven/commit/adc0d3bd6704fc16c54ddf75eab7fccbb33a5fe6"><code>adc0d3b</code></a>
[MNG-7800] Update to Resolver 1.9.11 (<a
href="https://redirect.github.com/apache/maven/issues/1140">#1140</a>)</li>
<li><a
href="https://github.com/apache/maven/commit/e6256065883f6c9c635fadcc393424b86290a8b0"><code>e625606</code></a>
[MNG-7811] Plugins verification - reporting improvements</li>
<li><a
href="https://github.com/apache/maven/commit/804b845c4d1cf4ea7d5f87584af01a7d6ff5e3a2"><code>804b845</code></a>
[3.9.x] Update some ancient build plugins (<a
href="https://redirect.github.com/apache/maven/issues/1165">#1165</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/apache/maven/compare/maven-3.9.2...maven-3.9.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.apache.maven:maven-model&package-manager=maven&previous-version=3.9.2&new-version=3.9.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Stig Strøm <stig.helge.strom@nav.no>