Bump org.springframework.boot:spring-boot-dependencies from 3.2.4 to 3.2.5 (#4497)
Bumps
[org.springframework.boot:spring-boot-dependencies](https://github.com/spring-projects/spring-boot)
from 3.2.4 to 3.2.5.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot:spring-boot-dependencies's
releases</a>.</em></p>
<blockquote>
<h2>v3.2.5</h2>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>BindValidationFailureAnalyzer uses wrong target <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40364">#40364</a></li>
<li>Log4j2LoggingSystem pollutes Log4j2's environment with a
SpringEnvironmentPropertySource that is never removed <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40326">#40326</a></li>
<li>When using Maven, configuring the spring-boot.excludes or
spring-boot-includes user properties causes the build to fail with
&quot;Cannot find default setter&quot; <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40323">#40323</a></li>
<li><code>@ServletComponentScan</code> does not register servlet
components in a mock web environment <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40321">#40321</a></li>
<li>Loading of custom deny-all filter can cause a StackOverflowError
when deploying to Tomcat with Log4j2 configured to use a single JVM-wide
logger context <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40312">#40312</a></li>
<li>Jetty support doesn't set virtual thread name <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40152">#40152</a></li>
<li>Executable JAR application startup is slower after 3.2.0 when
Hibernate scanner is not disabled <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40125">#40125</a></li>
<li>NoClassDefFoundError can be thrown from LaunchedClassLoader when
threads are interrupted <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40096">#40096</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Producible's javadoc has the wrong link text for
<code>@WriteOperation</code> and <code>@DeleteOperation</code> <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40386">#40386</a></li>
<li>Clarify requirements for -parameters and constructor binding <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/40157">#40157</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to ActiveMQ 5.18.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40394">#40394</a></li>
<li>Upgrade to AspectJ 1.9.22 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40293">#40293</a></li>
<li>Upgrade to Awaitility 4.2.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40294">#40294</a></li>
<li>Upgrade to Byte Buddy 1.14.13 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40295">#40295</a></li>
<li>Upgrade to Groovy 4.0.21 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40296">#40296</a></li>
<li>Upgrade to Hazelcast 5.3.7 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40297">#40297</a></li>
<li>Upgrade to Jakarta Json Bind 3.0.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40298">#40298</a></li>
<li>Upgrade to Jersey 3.1.6 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40299">#40299</a></li>
<li>Upgrade to Jetty 12.0.8 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40300">#40300</a></li>
<li>Upgrade to jOOQ 3.18.14 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40301">#40301</a></li>
<li>Upgrade to Json-smart 2.5.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40302">#40302</a></li>
<li>Upgrade to Kafka 3.6.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40303">#40303</a></li>
<li>Upgrade to Lombok 1.18.32 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40304">#40304</a></li>
<li>Upgrade to Maven Invoker Plugin 3.6.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40305">#40305</a></li>
<li>Upgrade to Maven Source Plugin 3.3.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40306">#40306</a></li>
<li>Upgrade to Micrometer 1.12.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40207">#40207</a></li>
<li>Upgrade to Micrometer Tracing 1.2.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40208">#40208</a></li>
<li>Upgrade to MongoDB 4.11.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40307">#40307</a></li>
<li>Upgrade to Neo4j Java Driver 5.19.0 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40218">#40218</a></li>
<li>Upgrade to Netty 4.1.109.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40395">#40395</a></li>
<li>Upgrade to Pulsar Reactive 0.5.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40396">#40396</a></li>
<li>Upgrade to R2DBC Postgresql 1.0.5.RELEASE <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40309">#40309</a></li>
<li>Upgrade to Reactor Bom 2023.0.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40209">#40209</a></li>
<li>Upgrade to SLF4J 2.0.13 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40397">#40397</a></li>
<li>Upgrade to Spring AMQP 3.1.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40210">#40210</a></li>
<li>Upgrade to Spring Authorization Server 1.2.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40211">#40211</a></li>
<li>Upgrade to Spring Data Bom 2023.1.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40212">#40212</a></li>
<li>Upgrade to Spring Framework 6.1.6 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40213">#40213</a></li>
<li>Upgrade to Spring GraphQL 1.2.6 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40310">#40310</a></li>
<li>Upgrade to Spring HATEOAS 2.2.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40376">#40376</a></li>
<li>Upgrade to Spring Integration 6.2.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/40214">#40214</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/b3a160db7d0e382a166204cfa3cbf548e9cd8ea7"><code>b3a160d</code></a>
Release v3.2.5</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f5b51ab74a2775ee52b0bc7c6684645025b7c3c1"><code>f5b51ab</code></a>
Merge branch '3.1.x' into 3.2.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/6b440723d6d72273fc3d0e6e8f51ea8eebbc97b3"><code>6b44072</code></a>
Remove dependency on the git ref when creating releases</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/b13d006482ced32590ebfe15247de02bf7d3d0e4"><code>b13d006</code></a>
Fix action that publishes to SDKman</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f84a2638a420810eebad58c1e44de5f2d5dd9722"><code>f84a263</code></a>
Merge branch '3.1.x' into 3.2.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/56b59cd02f09ef95375cf8d9eab22e52a69aaeb0"><code>56b59cd</code></a>
Fix action that publishes the Gradle plugin</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/9a28ae1316a857301ff7482f41d861bd98c75f4c"><code>9a28ae1</code></a>
Merge branch '3.1.x' into 3.2.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/18ada7cb917656bc7ee3778cb647e83a3cd5c87f"><code>18ada7c</code></a>
Next development version (v3.1.12-SNAPSHOT)</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/816b9b942ef857e04e6faea5ce5857df79d5128b"><code>816b9b9</code></a>
Merge branch '3.1.x' into 3.2.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/8a22108c625db3d61a2f847e673d64d5ee525d3a"><code>8a22108</code></a>
Use the version not the tag when creating the build name</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v3.2.4...v3.2.5">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot:spring-boot-dependencies&package-manager=maven&previous-version=3.2.4&new-version=3.2.5)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>