Bump org.springframework.boot:spring-boot-dependencies from 3.2.0 to 3.2.1 (#4262)
Bumps
[org.springframework.boot:spring-boot-dependencies](https://github.com/spring-projects/spring-boot)
from 3.2.0 to 3.2.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot:spring-boot-dependencies's
releases</a>.</em></p>
<blockquote>
<h2>v3.2.1</h2>
<h2>:star: New Features</h2>
<ul>
<li>Cleanup java sources <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38877">#38877</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>HibernateJpaAutoConfiguration should be applied before
DataSourceTransactionManagerAutoConfiguration <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38880">#38880</a></li>
<li>META-INF entries are duplicated under BOOT-INF/classes causing
&quot;Conflicting persistence unit definitions&quot; error <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38862">#38862</a></li>
<li>logging.include-application-name has no effect when using log4j2 <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38847">#38847</a></li>
<li>Pulsar authentication param properties cause IllegalStateException
with Pulsar Client 3.1.0 <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38839">#38839</a></li>
<li>Child context created with SpringApplicationBuilder runs parents
runners <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38837">#38837</a></li>
<li>getSigners() info is lost for signed jars when using the new loader
implementation with requiresUnpack <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38833">#38833</a></li>
<li>TestContainers parallel initialization doesn't work properly <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38831">#38831</a></li>
<li>Zip file closed exceptions can be thrown due to StaticResourceJars
closing jars from cached connections <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38770">#38770</a></li>
<li>Multi-byte filenames in zip files can cause an endless loop in
ZipString.hash <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38751">#38751</a></li>
<li>Gradle task &quot;bootJar&quot; fails with &quot;Failed to get
permissions&quot; when using Gradle 8.6-milestone-1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38741">#38741</a></li>
<li>Custom binding converters are ignored when working with collection
types <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38734">#38734</a></li>
<li>WebFlux and resource server auto-configuration may fail due to null
authentication manager <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38713">#38713</a></li>
<li>It is unclear that Docker Compose services have not been started as
one or more is already running <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38661">#38661</a></li>
<li>Spring Boot jar launcher does not work in folders containing certain
chars <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38660">#38660</a></li>
<li>FileNotFoundException is thrown eagerly from unused SSL bundles <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38659">#38659</a></li>
<li>NoUniqueBeanDefinitionFailureAnalyzer does not account for the fact
that missing '-parameters' may be the cause <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38652">#38652</a></li>
<li>Traces are propagated if tracing is disabled <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38641">#38641</a></li>
<li>Missing registry auto-configuration for JMS listener observation
support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38613">#38613</a></li>
<li>Class loading fails on an interrupted thread causing
com.mongodb.event.ServerClosedEvent to fail to load when Mongo detects a
cluster change <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38611">#38611</a></li>
<li>Failures due to code not being compiled with '-parameters' are hard
to identify <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38603">#38603</a></li>
<li>System SSL certificates are not used by the Apache HTTP Client in a
RestTemplate built with RestTemplateBuilder <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38600">#38600</a></li>
<li>ZipFileSystem throws &quot;java.util.zip.ZipException: read CEN
tables failed&quot; with certain nested jars <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38595">#38595</a></li>
<li>Nested jar URLs cannot be split and reassembled resulting in errors
with projects that use this technique (such as JobRunr) <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38592">#38592</a></li>
<li>NoSuchMethodError can be thrown from Session.getCookie() due to
binary incompatibilty <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38589">#38589</a></li>
<li>management.metrics.tags has been deprecated without a replacement
working for all metrics <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38583">#38583</a></li>
<li>NegativeArraySizeException can be thrown from
org.springframework.boot.loader.zip.ZipContent$Loader <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38572">#38572</a></li>
<li>Migration form 3.1.5 to 3.2.0 : &quot;Default&quot; Tracer is not
provided in test anymore <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38568">#38568</a></li>
<li>TomcatWebServer stop doesn't close sockets for additional connectors
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38564">#38564</a></li>
<li>Port is already in use when using <code>@SpringBootTest</code> with
a separate management port and a mock web environment <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38554">#38554</a></li>
<li>Keep-alive property causes processAot step to never finish <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38531">#38531</a></li>
<li>Setting 'spring.task.scheduling.shutdown.await-termination-period'
does not result in a call to
SimpleAsyncTaskScheduler#taskTerminationTimeout <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38530">#38530</a></li>
<li>Setting 'spring.task.execution.shutdown.await-termination-period'
does not result in a call to
SimpleAsyncTaskExecutor#taskTerminationTimeout <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38528">#38528</a></li>
<li>Nested URLs return null from classLoader.getResource(&quot;&quot;)
causing ClassPathResource failures <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38524">#38524</a></li>
<li>Spring Boot 3.2 is not compatible with older versions of Liquibase
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38522">#38522</a></li>
<li>Controller level exceptions not getting populated in HTTP server
requests metrics <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/33731">#33731</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Fix typo <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38879">#38879</a></li>
<li>Add the LangChain4J Spring Boot Starter to the list of community
starters <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38776">#38776</a></li>
<li>Document prerequisites for Docker Compose support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38764">#38764</a></li>
<li>Update Dynatrace documentation links <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38725">#38725</a></li>
<li>Correct references to Jetty's HTTP2 server module <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38632">#38632</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/8bb60eef026fc8787b5ac763bcb9c532f3fcb5f9"><code>8bb60ee</code></a>
Release v3.2.1</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/7d1982fc94c522afe06d89eece5b22d496d6e50b"><code>7d1982f</code></a>
Merge branch '3.1.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/53528d328585970f55f8b38291ec8f0d478dbfde"><code>53528d3</code></a>
Next development version (v3.1.8-SNAPSHOT)</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/3222458007b64561cb5918120b94206e3f6057b5"><code>3222458</code></a>
Merge branch '3.1.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/66e9c777af731cb96934f2a6fed1670512232b55"><code>66e9c77</code></a>
Upgrade Ubuntu version in CI images</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f31ffbf927468c953c845dcc87b258fe9de9a550"><code>f31ffbf</code></a>
Don't duplicate META-INF entries in nested directory jars</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/b2185282d40af03bbfa33ba3053851e029d7a6fa"><code>b218528</code></a>
Merge branch '3.1.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/20529ea90c1b5217355f9128b53bb82c75be3342"><code>20529ea</code></a>
Drop Netty restriction</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/bf7d1e4f7a06c785001fbea8d572adf10e803713"><code>bf7d1e4</code></a>
Merge branch '3.1.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/e754c91f50766e02dff4c3db1900715debfac2b6"><code>e754c91</code></a>
Upgrade to Spring WS 4.0.9</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v3.2.0...v3.2.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot:spring-boot-dependencies&package-manager=maven&previous-version=3.2.0&new-version=3.2.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>